serviceone:
    image: leodotcloud/swiss-army-knife
    environment:
        - NATO_ALPHABET=${S1_ALPHABET}

servicetwo:
    image: leodotcloud/swiss-army-knife
    labels:
      io.rancher.scheduler.global: true
    environment:
        - NATO_ALPHABET=${S2_ALPHABET}
    labels:
      io.rancher.sidekicks: servicetwosk

servicetwosk:
    image: leodotcloud/swiss-army-knife

servicethree:
    image: leodotcloud/swiss-army-knife
    environment:
        - NATO_ALPHABET=${S3_ALPHABET}
