serviceone:
    image: leodotcloud/swiss-army-knife
    environment:
        - NATO_ALPHABET=${S1_ALPHABET}
    labels:
      io.rancher.sidekicks: serviceonesk

serviceonesk:
    image: leodotcloud/swiss-army-knife

servicetwo:
    image: leodotcloud/swiss-army-knife
    environment:
        - NATO_ALPHABET=${S2_ALPHABET}
    links:
        - serviceone

servicethree:
    image: leodotcloud/swiss-army-knife
    environment:
        - NATO_ALPHABET=${S3_ALPHABET}
    links:
        - serviceone
        - servicetwo
