serviceone:
    image: leodotcloud/nato-alphabets
    environment:
        - NATO_ALPHABET=${S1_ALPHABET}

servicetwo:
    image: leodotcloud/nato-alphabets
    environment:
        - NATO_ALPHABET=${S2_ALPHABET}
    links:
        - serviceone

servicethree:
    image: leodotcloud/nato-alphabets
    environment:
        - NATO_ALPHABET=${S3_ALPHABET}
    links:
        - serviceone
        - servicetwo
