serviceone:
    image: leodotcloud/swiss-army-knife
    labels:
        com.rancher.stack.location: "phx"
        com.rancher.stack.size: "3"
    ports:
        - ${S1_PORT}:80
    environment:
        - NATO_ALPHABET=${S1_ALPHABET}

servicetwo:
    image: leodotcloud/swiss-army-knife
    labels:
        com.rancher.stack.location: "phx"
        com.rancher.stack.size: "3"
    ports:
        - ${S2_PORT}:80
    environment:
        - NATO_ALPHABET=${S2_ALPHABET}

servicethree:
    image: leodotcloud/swiss-army-knife
    labels:
        com.rancher.stack.location: "phx"
        com.rancher.stack.size: "3"
    ports:
        - ${S3_PORT}:80
    environment:
        - NATO_ALPHABET=${S3_ALPHABET}
