serviceone:
    image: leodotcloud/swiss-army-knife
    labels:
        com.rancher.stack.location: "sfo"
        com.rancher.stack.size: "2"
    ports:
        - ${S1_PORT}:80
    environment:
        - NATO_ALPHABET=${S1_ALPHABET}

servicetwo:
    image: leodotcloud/swiss-army-knife
    labels:
        com.rancher.stack.location: "sfo"
        com.rancher.stack.size: "2"
    ports:
        - ${S2_PORT}:80
    environment:
        - NATO_ALPHABET=${S2_ALPHABET}
